# Generated by Django 5.1 on 2025-11-06 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('biografia', models.TextField(help_text='Breve biografía del autor', verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Autor activo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del libro')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil')], max_length=3, verbose_name='Género')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('autores', models.ManyToManyField(related_name='libros', to='app_Libreria.autor', verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad vendida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la venta')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completada'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta')], default='PEN', max_length=3, verbose_name='Estado de la venta')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='app_Libreria.libro', verbose_name='Libro vendido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
