# Generated by Django 5.1 on 2025-11-10 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Libreria', '0004_delete_cliente_autor_created_at_autor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
